alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_STATUS_NORMATIV foreign key (STATUS_NORMATIV_ID) references BRATSK_STATUS_NORMATIV(ID);
create index IDX_BRATSK_MPA_ON_STATUS_NORMATIV on BRATSK_MPA (STATUS_NORMATIV_ID);
