-- begin BRATSK_MPA
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_APPROVER_USER foreign key (APPROVER_USER_ID) references SEC_USER(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_RELATION_TYPE_MPA_STATUS foreign key (RELATION_TYPE_MPA_STATUS_ID) references BRATSK_RELATION_TYPE_MPA(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_THEMATIC_PUBRIC foreign key (THEMATIC_PUBRIC_ID) references BRATSK_THEMA_RUBRIC(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_PREPARED foreign key (PREPARED_ID) references SEC_USER(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_EXECUTOR_USER foreign key (EXECUTOR_USER_ID) references SEC_USER(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_STATUS_NORMATIV foreign key (STATUS_NORMATIV_ID) references BRATSK_STATUS_NORMATIV(ID)^
alter table BRATSK_MPA add constraint FK_BRATSK_MPA_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_BRATSK_MPA_ON_APPROVER_USER on BRATSK_MPA (APPROVER_USER_ID)^
create index IDX_BRATSK_MPA_ON_RELATION_TYPE_MPA_STATUS on BRATSK_MPA (RELATION_TYPE_MPA_STATUS_ID)^
create index IDX_BRATSK_MPA_ON_THEMATIC_PUBRIC on BRATSK_MPA (THEMATIC_PUBRIC_ID)^
create index IDX_BRATSK_MPA_ON_PREPARED on BRATSK_MPA (PREPARED_ID)^
create index IDX_BRATSK_MPA_ON_EXECUTOR_USER on BRATSK_MPA (EXECUTOR_USER_ID)^
create index IDX_BRATSK_MPA_ON_STATUS_NORMATIV on BRATSK_MPA (STATUS_NORMATIV_ID)^
-- end BRATSK_MPA
-- begin BRATSK_RELATION_TYPE_MPA
alter table BRATSK_RELATION_TYPE_MPA add constraint FK_BRATSK_RELATION_TYPE_MPA_ON_REVERSE_NAME foreign key (REVERSE_NAME_ID) references BRATSK_RELATION_TYPE_MPA(ID)^
create unique index IDX_BRATSK_RELATION_TYPE_MPA_UK_TYPE_NAME on BRATSK_RELATION_TYPE_MPA (TYPE_NAME) where DELETE_TS is null ^
create index IDX_BRATSK_RELATION_TYPE_MPA_ON_REVERSE_NAME on BRATSK_RELATION_TYPE_MPA (REVERSE_NAME_ID)^
-- end BRATSK_RELATION_TYPE_MPA
-- begin BRATSK_RELATED_CARDS
alter table BRATSK_RELATED_CARDS add constraint FK_BRATSK_RELATED_CARDS_ON_SOURCE_CARD foreign key (SOURCE_CARD_ID) references WF_CARD(ID)^
alter table BRATSK_RELATED_CARDS add constraint FK_BRATSK_RELATED_CARDS_ON_RELATED_CARD foreign key (RELATED_CARD_ID) references WF_CARD(ID)^
alter table BRATSK_RELATED_CARDS add constraint FK_BRATSK_RELATED_CARDS_ON_SOURCE_RELATION_TYPE foreign key (SOURCE_RELATION_TYPE_ID) references BRATSK_RELATION_TYPE_MPA(ID)^
alter table BRATSK_RELATED_CARDS add constraint FK_BRATSK_RELATED_CARDS_ON_RELATED_RELATION_TYPE foreign key (RELATED_RELATION_TYPE_ID) references BRATSK_RELATION_TYPE_MPA(ID)^
create index IDX_BRATSK_RELATED_CARDS_ON_SOURCE_CARD on BRATSK_RELATED_CARDS (SOURCE_CARD_ID)^
create index IDX_BRATSK_RELATED_CARDS_ON_RELATED_CARD on BRATSK_RELATED_CARDS (RELATED_CARD_ID)^
create index IDX_BRATSK_RELATED_CARDS_ON_SOURCE_RELATION_TYPE on BRATSK_RELATED_CARDS (SOURCE_RELATION_TYPE_ID)^
create index IDX_BRATSK_RELATED_CARDS_ON_RELATED_RELATION_TYPE on BRATSK_RELATED_CARDS (RELATED_RELATION_TYPE_ID)^
-- end BRATSK_RELATED_CARDS

-- begin BRATSK_THEMA_RUBRIC
alter table BRATSK_THEMA_RUBRIC add constraint FK_BRATSK_THEMA_RUBRIC_ON_PARENT_THEMA_RUBRIC foreign key (PARENT_THEMA_RUBRIC_ID) references BRATSK_THEMA_RUBRIC(ID)^
create index IDX_BRATSK_THEMA_RUBRIC_ON_PARENT_THEMA_RUBRIC on BRATSK_THEMA_RUBRIC (PARENT_THEMA_RUBRIC_ID)^
-- end BRATSK_THEMA_RUBRIC
